/*
  Dynamic Reader

  The dynamic code reader reads in the logfile generated by
  the post-injection codebase. It then uses the Colourizer
  and Linker to put the function call data into a format/
  data structure that the Graph Maker can use to determine
  the appropriate UbiGraph calls
*/
#include <iostream>
#include <stdio.h>
#include <dirent.h>
#include <fstream>
#include <string>
#include "DynamicReader.h"
#include "Colourizer.h"
#include "Linker.h"

using namespace std;

int main(void){
  ifstream logfile;
  string currLine;
  logfile.open(); // insert path to log generated
  getline(infile, currLine);
  logfile.close();
  while (!infile.eof()){
    // some logic to parse the log
    // some tree-building code to store it
    // some Colourizer logic
    // some Linker logic
  }
}
